export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_NUMBER_CART = "GET_NUMBER_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
